# Generated by Django 5.2.4 on 2025-08-13 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Courses',
        ),
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='Enrollments',
        ),
        migrations.RenameModel(
            old_name='Grade',
            new_name='Grades',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
