# Generated by Django 5.2.4 on 2025-08-23 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_course_courses_rename_enrollment_enrollments_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='Enrollments',
            new_name='Enrollment',
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_value', models.CharField(max_length=2)),
                ('grade_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField()),
                ('enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.enrollment')),
            ],
            options={
                'unique_together': {('enrollment_id', 'grade_value')},
            },
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
