# Generated by Django 5.2.4 on 2025-08-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_courses_course_rename_students_student_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grade_value',
        ),
    ]
